name: Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    Linting:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            - name: Add problem matcher
              run: echo "::add-matcher::.github/problemMatchers/eslint.json"
            - name: Use Node.js v16
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
              with:
                  node-version: 16
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Run ESLint
              run: yarn lint --fix=false

    Testing:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            - name: Use Node.js v16
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
              with:
                  node-version: 16
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Run tests
              run: yarn test --coverage
            - name: Run type tests
              run: yarn test:typecheck
            - name: Store code coverage report
              uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
              with:
                  name: coverage
                  path: coverage/

    Building:
        name: Compile source code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
            - name: Add problem matcher
              run: echo "::add-matcher::.github/problemMatchers/tsc.json"
            - name: Use Node.js v16
              uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
              with:
                  node-version: 16
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              run: yarn --immutable
            - name: Build Code
              run: yarn build

    # Upload_Coverage_Report:
    #     name: Upload coverage report to codecov
    #     needs: [Testing]
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Project
    #           uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3
    #           with:
    #               fetch-depth: 2
    #         - name: Download Coverage report
    #           uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
    #           with:
    #               name: coverage
    #               path: coverage/
    #         - name: Codecov Upload
    #           uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # tag=v3
    #           with:
    #               token: ${{ secrets.CODECOV_TOKEN }}
    #               directory: coverage/
    #               fail_ci_if_error: true
